name: Wix Prototypers
title: Workspace 2.0

ux_owner: "Ido Back"
prototyper: "Yuval Pinhas"
date_created: "March 2022"

variations:
  - name: "Design Area"
    description: "Focus on design area: adding & removing items, drill in to widgets."
    # Url contains everything that comes after https://wix-prototypers.github.io/
    # e.g: /editor_project-name/project-name_01_variation-name
    url: "workspace-2.0_01 "

useful_links:
  - name: "Figma"
    url: "https://www.figma.com/file/hbJ0A9sBkiuUqPurPBvxVN/Workspace-2.02"
  - name: "Presentation"
    url: "https://docs.google.com/presentation/d/1omoZqgSqPbyZ1Irex5bXjDH12mbgxmNjyNW9BH3Lf_Y/edit#slide=id.gb7277700ec_0_0"
